[package]
name = "gurftron_db"
version = "0.1.0"
authors = ["Adeyeye George"]
description = "Enhanced decentralized database with security and rewards"

[dependencies]
starknet = "2.8.2"

[cairo]
sierra = "2.8.2"

[scripts]
test = "scarb cairo-test"