[package]
name = "gurftron_db"
version = "0.1.0"
authors = ["Adeyeye George David"]
description = "Enhanced decentralized database with security and reward system"
edition = "2024_07"
cairo-version = "2.8.0"
license = "MIT"

[dependencies]
starknet = "2.7.0"

[dev-dependencies]
cairo_test = "2.12.2"

[[target.starknet-contract]]
sierra = true
casm = true
